### ISSUE TITLE
docker without --user 1000

### ISSUE THREAD

**Issue by am11** [perlpunk/yaml-runtimes#1]
When we run a container with `docker run --user 1000 -it ...` command, `echo $HOME` returns `/`, where this non-existing user (`whoami: unknown uid 1000`) does not have permission to.

Three possible solutions tested so far (in the ascending order of preference):

1. `export HOME=/tmp` (or somewhere where this unknown user has rights) in `docker/{lang}/utils/{lang}-{library}.sh`
2. remove `--user` and let it run as root (`run as root` generally raises eyebrow, but (empirically speaking) `run as root in container` is comparatively palatable for builder-like containers).
3. create a user group and user:
    ```sh
    mkdir emptyDir; cd $_

    cat << EOF > Dockerfile
    FROM alpine
    RUN addgroup -S yamlgroup && adduser -S yamlbuilder -G yamlgroup
    USER yamlbuilder  # will execute all subsequent commands as 'yamlbuilder'
    EOF

    docker build -t yamlbuilder-alpine .
    docker run -it yamlbuilder-alpine  # without `--user` argument
    ```

**Comment by perlpunk** [comment]
Yeah; so far I only needed to set `HOME=/tmp/home` in the build scripts, so option 1.
But I just had another idea:
`docker run ... --env HOME=/tmp/home`
Then the build scripts won't have to do this.

Option 2 is something I want to avoid. Also because then we need to set permissions on all created files  outside of the container.

Option 3 would of course be nice, but actually has the same problem - the files will be owned by a different userid (it might be the same of course by coincidence).

I'll try out the `--env` thing.

**Comment by perlpunk** [comment]
I just pushed that to `dev`

**Comment by am11** [comment]
Thank you for pushing the quick fix. I will finish the .NET container tomorrow after the Core 3.0 release. :)

> outside of the container

Little curiosity; where would they be used outside of the container, another container? Because C/C++ and .NET (single-file published) produced binaries are explicitly linked against musl-libc in alpine container, they will be portable for musl-libc based distros (Alpine, Void, Sabotage etc.).

**Comment by perlpunk** [comment]
> Little curiosity; where would they be used outside of the container,

Oh, I just meant that the files will be written to the mounted `/build` directory for copying from builder to runtime. Without `--user ...` they will belong to user root, and then you cannot easily delete them if you need to.

I hope you don't get much conflicts, I changed a couple of things yesterday :)

Btw, a general thing, if you need to update something to current master, please always use `rebase` and don't merge master into the PR.
I will add a contributor guideline the next days.

**Comment by perlpunk** [comment]
Fixed via 5a82168

**Comment by am11** [comment]
I am not blocked by this, but just found during troubleshooting a separate build error that unknown user inside the docker also refrains us from using `sudo`, `sudo: unknown uid 1000: who are you?`. Another approach could be to `adduser` with `--uuid $<` in `build.pl` when invoking `docker run` (or a wrapper script?).

However, this approach of overriding default command would forgo the flexibility between builder-docker and builder-script; today builder-docker can expose `CMD` or entrypoint with for example `command -v ruby` and builder-script can be `.rb` file. Although, currently we are not using default `CMD` in builder dockers and it might be an ok tradeoff.

**Comment by perlpunk** [comment]
Ok, I don't know how the build process of .NET and its YAML library works =)
So far, every build script is able to install the YAML library to a specified directory, for eample with `--prefix`. If this is not possible with .NET, we can think about adding an extra option to the `list.yaml` file to run the build as root.
In your PR for yaml-editor https://github.com/yaml/yaml-editor/pull/21 I didn't see anything that looks like it needs root privileges

**Comment by am11** [comment]
Yup, not related to .NET or any particular library. I am just pointing out possible fallouts of unknown uid, `sudo` and `whoami` tools were unhappy, there might be others. :)
